version: '2'
services:
    objectif_dty-app:
        image: objectif_dty
        external_links:
            - objectif_dty-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/objectif_dty?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    objectif_dty-mysql:
        extends:
            file: mysql.yml
            service: objectif_dty-mysql
