version: '2'
services:
    objectif_dty-mysql:
        container_name: objectif_dty-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/objectif_dty/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=objectif_dty
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
